### ISSUE TITLE
Add autocomplete on physical_mode for forbidden_uris[]

### ISSUE THREAD

**Issue by pbougue** [CanalTP/navitia-playground#133] opened 2016-06-16 06:06 UTC
Not sure it's easy to do, though... maybe a call to /physical_modes ?

**Comment by TeXitoi** [comment] 2016-06-16 07:13
The problem is mixing the autocomplete. You can't have a good solution. IMO, it should be fixed by navitia.

**Comment by TeXitoi** [comment] 2017-02-11 13:28
The fix must be in navitia

**Closed by TeXitoi** 2017-02-11 13:28 UTC
Labels: question, wontfix
