### ISSUE TITLE
How to get a token

### ISSUE THREAD

**Issue by stifoon** [CanalTP/navitia-playground#230] opened 2016-12-05 10:55 UTC
Could it be possible to have a link to get a token on https://www.navitia.io/register/ ?

Maybe near the floppy disk on http://canaltp.github.io/navitia-playground/play.html or anywhere else where it could be understandable :)

**Comment by TeXitoi** [comment] 2016-12-05 11:24
duplicate of #177 but that's a good proposition.

**Closed by TeXitoi** 2016-12-05 11:24 UTC
